name: Create terraform plan

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create a plan for an example terraform configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform plan
        run: |
          terraform plan -var "application_client_id=$APPLICATION_ID" -var "subscription_id=$SUBSCRIPTION_ID" -var "directory_tenant_id=$DIRECTORY_ID" -var "client_secret=$CLIENT_SECRET" 
        env:
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          DIRECTORY_ID: ${{ secrets.DIRECTORY_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
