name: Terraform Apply - Azure

on:
  push:
    branches:
      - main

jobs:
  terraform_apply_azure:
    runs-on: ubuntu-latest
    name: terraform apply - azure
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform apply
        run: |
          cd ./azure/infra
          terraform init
          terraform apply 
        env:
          ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TENANT_ID }}