name: Terraform Plan - Azure

on: [pull_request]

jobs:
  terraform_plan_azure:
    runs-on: ubuntu-latest
    name: terraform plan - azure
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform plan
        run: |
          cd ./azure/infra
          export ARM_CLIENT_SECRET=$CLIENT_SECRET
          terraform init
          terraform plan -var "client_secret=$CLIENT_SECRET" 
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
