name: Terraform Destroy - Azure

on: workflow_dispatch

jobs:
  terraform_destroy_azure:
    runs-on: ubuntu-latest
    name: terraform destroy - azure
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform destroy
        run: |
          cd ./azure/infra
          terraform init
          terraform destroy -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TENANT_ID }}