name: Terraform Plan - Azure

on: [pull_request]

jobs:
  terraform_plan_azure:
    runs-on: ubuntu-latest
    name: terraform plan - azure
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform plan
        run: |
          cd ./azure/infra
          terraform init
          terraform plan 
        env:
          ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TENANT_ID }}